import type { LayerType } from "@/lib/types";

// Colors used in both the editor and the PDF composer (synced via this single source).
export const LAYER_STYLES: Record<LayerType, { color: string; fillColor: string; fillOpacity: number; weight: number; dashArray?: string }> = {
  lease_boundary:           { color: "#0f172a", fillColor: "#0f172a", fillOpacity: 0.05, weight: 2.5 },
  statutory_barrier_7_5m:   { color: "#dc2626", fillColor: "#dc2626", fillOpacity: 0.08, weight: 1.5, dashArray: "6 4" },
  boundary_60m:             { color: "#7c3aed", fillColor: "#7c3aed", fillOpacity: 0.05, weight: 1, dashArray: "4 4" },
  boundary_500m:            { color: "#7c3aed", fillColor: "#7c3aed", fillOpacity: 0.03, weight: 1, dashArray: "4 4" },
  grid_lines:               { color: "#94a3b8", fillColor: "#94a3b8", fillOpacity: 0, weight: 0.5, dashArray: "2 4" },
  contour:                  { color: "#a16207", fillColor: "#a16207", fillOpacity: 0, weight: 0.7 },
  road:                     { color: "#334155", fillColor: "#334155", fillOpacity: 0, weight: 2 },
  existing_tank:            { color: "#0ea5e9", fillColor: "#0ea5e9", fillOpacity: 0.3, weight: 1.5 },
  existing_infrastructure:  { color: "#525252", fillColor: "#a3a3a3", fillOpacity: 0.3, weight: 1.5 },
  existing_electric_line:   { color: "#eab308", fillColor: "#eab308", fillOpacity: 0, weight: 1.5, dashArray: "8 4" },
  existing_borehole:        { color: "#1d4ed8", fillColor: "#3b82f6", fillOpacity: 0.5, weight: 1 },
  proposed_borehole:        { color: "#1d4ed8", fillColor: "#93c5fd", fillOpacity: 0.5, weight: 1, dashArray: "3 3" },
  geological_zone:          { color: "#a16207", fillColor: "#fde68a", fillOpacity: 0.3, weight: 1 },
  ultimate_pit_limit:       { color: "#7c2d12", fillColor: "#7c2d12", fillOpacity: 0.12, weight: 2, dashArray: "10 4" },
  year_pit:                 { color: "#ea580c", fillColor: "#fed7aa", fillOpacity: 0.45, weight: 1.5 },
  overburden_dump:          { color: "#78350f", fillColor: "#d6a575", fillOpacity: 0.5, weight: 1 },
  topsoil_stack:            { color: "#92400e", fillColor: "#fbbf24", fillOpacity: 0.5, weight: 1 },
  backfill:                 { color: "#365314", fillColor: "#a3e635", fillOpacity: 0.45, weight: 1 },
  plantation:               { color: "#166534", fillColor: "#86efac", fillOpacity: 0.55, weight: 1 },
  mineral_stack_yard:       { color: "#7e22ce", fillColor: "#d8b4fe", fillOpacity: 0.5, weight: 1 },
  haul_road:                { color: "#1f2937", fillColor: "#1f2937", fillOpacity: 0, weight: 3 },
  garland_drain:            { color: "#0284c7", fillColor: "#0284c7", fillOpacity: 0, weight: 1.5, dashArray: "6 3" },
  settling_tank:            { color: "#0369a1", fillColor: "#7dd3fc", fillOpacity: 0.6, weight: 1.5 },
  retaining_wall:           { color: "#404040", fillColor: "#404040", fillOpacity: 0, weight: 2 },
  fencing:                  { color: "#525252", fillColor: "#525252", fillOpacity: 0, weight: 1, dashArray: "3 3" },
  office_shed:              { color: "#525252", fillColor: "#d4d4d8", fillOpacity: 0.7, weight: 1 },
  water_reservoir:          { color: "#0369a1", fillColor: "#7dd3fc", fillOpacity: 0.5, weight: 1.5 },
  village:                  { color: "#b45309", fillColor: "#fde68a", fillOpacity: 0.5, weight: 1 },
  sensitive_structure:      { color: "#be123c", fillColor: "#fda4af", fillOpacity: 0.5, weight: 1 },
};

export const LAYER_LABELS: Record<LayerType, string> = {
  lease_boundary: "Lease Boundary",
  statutory_barrier_7_5m: "7.5 m Statutory Barrier",
  boundary_60m: "60 m Boundary",
  boundary_500m: "500 m Boundary",
  grid_lines: "Grid Lines",
  contour: "Contour",
  road: "Road / Rasta",
  existing_tank: "Existing Tank",
  existing_infrastructure: "Existing Infrastructure",
  existing_electric_line: "Existing Electric Line",
  existing_borehole: "Existing Borehole",
  proposed_borehole: "Proposed Borehole",
  geological_zone: "Geological Zone",
  ultimate_pit_limit: "Ultimate Pit Limit",
  year_pit: "Year Pit",
  overburden_dump: "Overburden Dump",
  topsoil_stack: "Topsoil Stack",
  backfill: "Backfill",
  plantation: "Plantation",
  mineral_stack_yard: "Mineral Stack Yard",
  haul_road: "Haul Road",
  garland_drain: "Garland Drain",
  settling_tank: "Settling Tank",
  retaining_wall: "Retaining Wall",
  fencing: "Fencing",
  office_shed: "Office / Labour Shed",
  water_reservoir: "Water Reservoir",
  village: "Village",
  sensitive_structure: "Sensitive Structure",
};
