"""Per-year statutory plate composer.

Renders one year's development plan, modelled after the reference plate
(Plate 5A — Year I Development Plan, Haripura Limestone Block TKSB-18):

  - Year N pit highlighted (bright fill)
  - Faint outlines of all years 1..N (cumulative pit history)
  - Year N cumulative OB / topsoil / plantation
  - Lease boundary + 7.5 m statutory barrier
  - Haul road
  - All boreholes (existing + proposed)
  - "DIRECTION OF NEXT YEAR" arrow from Year N pit centroid to Year N+1
    pit centroid (omitted on the final year's plate)
  - Title block reading "PROPOSED Nth YEAR DEVELOPMENT PLAN OF {name}"
  - Plate number: 5A / 5B / 5C / 5D / 5E for years 1-5
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any

import matplotlib

matplotlib.use("Agg")

import cartopy.crs as ccrs  # noqa: E402
import matplotlib.patches as mpatches  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402
from pyproj import Transformer  # noqa: E402
from shapely.geometry import shape  # noqa: E402

from services.pdf_composer import (  # noqa: E402
    CERTIFICATION_TEXT, LAYER_STYLE, PAPER_INCHES, YEAR_COLORS,
    _compute_extent, _draw_geom, _draw_north_arrow, _draw_scale_bar,
    _geom_to_utm, _round_scale_length,
)


ORDINALS = ["", "1st", "2nd", "3rd", "4th", "5th"]
PLATE_LETTERS = ["", "A", "B", "C", "D", "E"]

# Layers always carried over from the source data (or generated by the
# planner) onto every year-plate.
ALWAYS_LAYERS = {
    "lease_boundary", "statutory_barrier_7_5m", "ultimate_pit_limit",
    "haul_road", "garland_drain", "settling_tank",
    "existing_borehole", "proposed_borehole",
    "road", "existing_tank", "existing_infrastructure", "village",
    "sensitive_structure", "water_reservoir", "existing_electric_line",
    "geological_zone",
}

# Layers whose 'year' tag picks the single feature to draw on this plate.
YEAR_TAGGED_LAYERS = {"year_pit", "overburden_dump", "topsoil_stack", "plantation"}


def compose_year_plate(
    project: dict[str, Any],
    *,
    alternative: str,
    year: int,
    paper: str = "A3",
    orientation: str = "landscape",
    scale: int = 1000,
) -> bytes:
    """Render the year-N development plan for `alternative` and return PDF bytes."""
    key = f"{paper}_{orientation}"
    if key not in PAPER_INCHES:
        raise ValueError(f"Unsupported paper/orientation: {key}")
    fig_size = PAPER_INCHES[key]

    details = project.get("project_details") or {}
    plan_years = int(details.get("plan_period_years") or 5)
    plan_years = max(1, min(5, plan_years))
    if not (1 <= year <= plan_years):
        raise ValueError(f"year must be 1..{plan_years}, got {year}")

    plan = next((p for p in (project.get("generated_plans") or []) if p["alternative"] == alternative), None)
    if plan is None:
        raise ValueError(f"No generated plan for alternative {alternative}")

    # Collect features from the plan + the user-digitized layers
    all_features = list(plan["features"]["features"])
    for f in (project.get("digitized_layers") or {}).get("features", []):
        if f.get("properties", {}).get("layer_type") in ALWAYS_LAYERS:
            all_features.append(f)

    # Convert to UTM
    utm_features: list[tuple[dict[str, Any], Any]] = []
    for f in all_features:
        try:
            utm_features.append((f["properties"], _geom_to_utm(f["geometry"])))
        except Exception:
            continue

    # Year-pit centroids for arrows + faint history outlines
    year_pit_utm: dict[int, Any] = {}
    for props, geom in utm_features:
        if props.get("layer_type") == "year_pit" and isinstance(props.get("year"), int):
            year_pit_utm[props["year"]] = geom

    # Partition: always-keep, this-year-only (for YEAR_TAGGED_LAYERS),
    # and prior-year outlines for year_pit
    keep: list[tuple[dict[str, Any], Any]] = []
    for props, geom in utm_features:
        lt = props.get("layer_type")
        yr = props.get("year")
        if lt in YEAR_TAGGED_LAYERS:
            if yr == year:
                keep.append((props, geom))
        elif lt in ALWAYS_LAYERS:
            keep.append((props, geom))
        # else (untagged OB/topsoil/plantation): skip — superseded by per-year
    if not keep:
        raise ValueError(f"Year {year} has no features to draw.")

    fig = plt.figure(figsize=fig_size, dpi=200)
    fig.patch.set_facecolor("white")

    border_ax = fig.add_axes((0.02, 0.02, 0.96, 0.96))
    border_ax.axis("off")
    border_ax.add_patch(mpatches.Rectangle((0, 0), 1, 1, transform=border_ax.transAxes,
                                           edgecolor="#0f172a", facecolor="none", linewidth=1.5))

    ax = fig.add_axes((0.04, 0.28, 0.78, 0.66), projection=ccrs.epsg(32643))
    ax.set_facecolor("#f8fafc")
    extent = _compute_extent([g for (_, g) in keep], fig_size, scale)
    ax.set_xlim(extent[0], extent[2])
    ax.set_ylim(extent[1], extent[3])
    try:
        gl = ax.gridlines(draw_labels=True, linewidth=0.4, color="#94a3b8", alpha=0.7)
        gl.top_labels = False; gl.right_labels = False
        gl.xlabel_style = {"size": 7, "color": "#475569"}
        gl.ylabel_style = {"size": 7, "color": "#475569"}
    except Exception:
        pass

    # 1. Faint outlines of prior years' pits (history) — drawn first so they
    #    sit under everything else
    for y_prev in range(1, year):
        prev_geom = year_pit_utm.get(y_prev)
        if prev_geom is None:
            continue
        _draw_geom(ax, prev_geom, {
            "edgecolor": "#94a3b8", "facecolor": "none",
            "linewidth": 0.6, "linestyle": (0, (3, 2)), "zorder": 2,
        })
        c = prev_geom.centroid
        ax.text(c.x, c.y, f"Y{y_prev}", fontsize=7, color="#94a3b8",
                ha="center", va="center", zorder=3)

    # 2. Everything else — usual styling, with year_pit getting the year color
    used_keys: list[str] = []
    for props, geom in keep:
        lt = props.get("layer_type")
        if lt not in LAYER_STYLE:
            continue
        style = dict(LAYER_STYLE[lt])
        if lt == "year_pit":
            style["facecolor"] = YEAR_COLORS[(year - 1) % len(YEAR_COLORS)]
        _draw_geom(ax, geom, style)
        if lt not in used_keys:
            used_keys.append(lt)

    # 3. Label the active year pit
    active_pit = year_pit_utm.get(year)
    if active_pit is not None:
        c = active_pit.centroid
        ax.text(c.x, c.y, f"YEAR {year}", fontsize=11, fontweight="bold",
                color="#7c2d12", ha="center", va="center", zorder=20)

    # 4. Direction-of-next-year arrow (omit on final year)
    next_pit = year_pit_utm.get(year + 1)
    if active_pit is not None and next_pit is not None:
        from_xy = active_pit.centroid
        to_xy = next_pit.centroid
        ax.annotate(
            "", xy=(to_xy.x, to_xy.y), xytext=(from_xy.x, from_xy.y),
            arrowprops=dict(arrowstyle="->", color="#0f172a", lw=1.8,
                            shrinkA=15, shrinkB=15), zorder=21,
        )
        mid_x = (from_xy.x + to_xy.x) / 2
        mid_y = (from_xy.y + to_xy.y) / 2
        ax.text(mid_x, mid_y, f"DIRECTION OF\nYEAR {year + 1}", fontsize=8,
                fontweight="bold", color="#0f172a",
                ha="center", va="center", zorder=22,
                bbox=dict(boxstyle="round,pad=0.25", facecolor="#fef3c7",
                          edgecolor="#0f172a", linewidth=0.6))

    # 5. Chrome
    title = f"PROPOSED {ORDINALS[year]} YEAR DEVELOPMENT PLAN — Scale 1:{scale}"
    ax.set_title(title, fontsize=12, fontweight="bold", color="#0f172a", pad=10)

    map_width_m = extent[2] - extent[0]
    bar_len = _round_scale_length(map_width_m * 0.18)
    _draw_scale_bar(ax, bar_len, f"{int(bar_len)} m")

    _draw_north_arrow(fig, x_norm=0.045, y_norm=0.88)
    _draw_legend(fig, used_keys, year=year)
    _draw_title_block(fig, details, scale=scale, alternative=alternative, year=year, plan_years=plan_years)
    _draw_certification(fig)

    buf = io.BytesIO()
    fig.savefig(buf, format="pdf", bbox_inches=None, dpi=300)
    plt.close(fig)
    return buf.getvalue()


def _draw_legend(fig, used_keys: list[str], *, year: int) -> None:
    handles = []
    labels = []
    for k in used_keys:
        st = LAYER_STYLE.get(k)
        if not st:
            continue
        label_prefix = ""
        if k == "year_pit":
            handles.append(mpatches.Patch(
                facecolor=YEAR_COLORS[(year - 1) % len(YEAR_COLORS)],
                edgecolor="#9a3412", linewidth=0.6,
            ))
            labels.append(f"Year {year} Mine Working")
            continue
        if k in {"overburden_dump", "topsoil_stack", "plantation"}:
            label_prefix = f"Year {year} "
        if "facecolor" in st and st["facecolor"] != "none":
            handles.append(mpatches.Patch(
                facecolor=st["facecolor"], edgecolor=st["edgecolor"],
                alpha=st.get("alpha", 1.0), hatch=st.get("hatch"),
                linewidth=st.get("linewidth", 1),
            ))
        else:
            handles.append(Line2D([], [], color=st["edgecolor"], linewidth=st["linewidth"],
                                  linestyle=st.get("linestyle", "-")))
        from services.pdf_composer import LAYER_LABEL
        labels.append(label_prefix + LAYER_LABEL.get(k, k))
    # also a row for the faint prior-year outlines
    if year > 1:
        handles.append(Line2D([], [], color="#94a3b8", linewidth=0.6, linestyle=(0, (3, 2))))
        labels.append("Prior years' pits (history)")

    ax = fig.add_axes((0.84, 0.28, 0.14, 0.58))
    ax.axis("off")
    ax.add_patch(mpatches.Rectangle((0, 0), 1, 1, transform=ax.transAxes,
                                    edgecolor="#475569", facecolor="white", linewidth=0.8))
    ax.text(0.5, 0.97, "INDEX", transform=ax.transAxes, fontsize=10, fontweight="bold",
            ha="center", va="top")
    ax.legend(handles, labels, loc="upper left", bbox_to_anchor=(0.05, 0.93),
              frameon=False, fontsize=7, handlelength=2, labelspacing=0.55)


def _draw_title_block(fig, details: dict[str, Any], *, scale: int,
                      alternative: str, year: int, plan_years: int) -> None:
    ax = fig.add_axes((0.62, 0.04, 0.36, 0.22))
    ax.axis("off")
    ax.add_patch(mpatches.Rectangle((0, 0), 1, 1, transform=ax.transAxes,
                                    edgecolor="#0f172a", facecolor="white", linewidth=1.2))
    title_line = f"PROPOSED {ORDINALS[year]} YEAR DEVELOPMENT PLAN OF {details.get('project_name', '').upper()}"
    plate_no = f"5{PLATE_LETTERS[year]}"
    lines = [
        title_line,
        f"N/v – {details.get('village', '')}, Tehsil – {details.get('tehsil', '')}, "
        f"Distt. – {details.get('district', '')} ({details.get('state', '')})",
        f"Mineral – {details.get('mineral', '')}",
        f"Applicant – {details.get('applicant_name', '')}",
        f"Area – {details.get('area_ha', '')} Hect. · Scale – 1:{scale}",
        f"Approach – {alternative} · Year {year} of {plan_years}",
        f"Survey date – {details.get('survey_date', '—')}",
        f"Plate prepared – {datetime.now().strftime('%d-%m-%Y')}",
        f"PLATE NO. – {plate_no}",
    ]
    y = 0.93
    for i, ln in enumerate(lines):
        ax.text(0.04, y, ln, transform=ax.transAxes,
                fontsize=8.5 if i > 0 else 10,
                fontweight="bold" if i == 0 or i == len(lines) - 1 else "normal",
                color="#0f172a" if i != len(lines) - 1 else "#b91c1c",
                va="top")
        y -= 0.10


def _draw_certification(fig) -> None:
    ax = fig.add_axes((0.04, 0.04, 0.55, 0.10))
    ax.axis("off")
    ax.add_patch(mpatches.Rectangle((0, 0), 1, 1, transform=ax.transAxes,
                                    edgecolor="#b91c1c", facecolor="#fef2f2", linewidth=1.0))
    ax.text(0.02, 0.85, "CERTIFICATION", transform=ax.transAxes,
            fontsize=9, fontweight="bold", color="#b91c1c", va="top")
    ax.text(0.02, 0.65, CERTIFICATION_TEXT, transform=ax.transAxes,
            fontsize=7.5, color="#7f1d1d", va="top", wrap=True)
